### ISSUE TITLE
Share server push strategies

### ISSUE THREAD

**Issue by MartinsThiago** [Polymer/news#132]
It would be really interesting to know how you guys have setup your server (nginx I assume) to play nicely with Server Push

Here is the list of what I'd like to know:
- Did you automate the deploy to automatically detect what resources are pushed?
- Do different routes push same resources?
- Why nginx this time? (polymer-shop is served through apache-server)

Share with us please :smiley:

**Comment by frankiefu** [comment]
We put all the config generation and scripts for managing SHOP and NEWS in the new nghttpx+nginx architecture to the [prpl-rain](https://github.com/PolymerLabs/prpl-rain) repo.  It's still WIP so feel free to take a look if anything there is useful for you.

cc @usergenic

**Comment by MartinsThiago** [comment]
Nice, I am really thinking about hosting my polymer app by myself... Actually my frontend is being hosted by a third party (Netlify)... Which is good for me, but they have no server push (at least for now)

Server push is crucial for me when I enter in production, 3g connections here in Brazil are really poor ¯\\\_(ツ)_/¯ and I don't want to send my entire app in a bundle

**Comment by MartinsThiago** [comment]
I'll keep my eyes on prpl-rain [prpl-rain](https://github.com/PolymerLabs/prpl-rain)

**Comment by muhajirframe** [comment]
They have it now @MartinsThiago
