### ISSUE TITLE
When sharing on Social Media such as Twitter & Google+, metadata is not displayed

### ISSUE THREAD

**Issue by a-haan** [Polymer/news#133]
Tested on my own version https://ahaan.co.uk and https://news.polymer-project.org/

**Comment by frankiefu** [comment]
We added the social meta tags to the articles.  If you share the articles (e.g https://news.polymer-project.org/article/top_stories/experience-daydream-today), that should display the right info.

<img width="1005" alt="screen shot 2017-02-27 at 1 50 21 pm" src="https://cloud.githubusercontent.com/assets/116360/23381563/cc9babcc-fcf3-11e6-80f8-ae3c2fbd6cc7.png">

**Comment by a-haan** [comment]
after closer inspection, It looks like Twitter works fine, it can read the metadata of the article but Google+ fails to read any of my tags - it will only read tags on index.html - any help will be appreciated.

**Comment by frankiefu** [comment]
Seems like we are missing [`Google (+https://developers.google.com/+/web/snippet/)`](https://gist.github.com/thoop/8072354#gistcomment-1415155) in the [UA list](https://github.com/Polymer/news/blob/master/main.py).  Can you try adding this to see if that helps?

**Comment by a-haan** [comment]
I can confirm after adding in 'developers\.google\.com\/\+\/web\/snippet\/' sharing to Google+ works beautifully.  Thank you Frankiefu!!
